/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#273647",
        "error": "#ffb4ab",
        "on-secondary-fixed": "#2c0051",
        "primary-fixed-dim": "#d2bbff",
        "tertiary-fixed": "#c4e7ff",
        "on-primary": "#3f008e",
        "on-primary-fixed": "#25005a",
        "surface": "#051424",
        "primary-fixed": "#eaddff",
        "secondary-fixed": "#f0dbff",
        "surface-container-lowest": "#010f1f",
        "tertiary": "#7bd0ff",
        "outline-variant": "#4a4455",
        "on-error-container": "#ffdad6",
        "on-secondary": "#490080",
        "on-primary-container": "#ede0ff",
        "on-secondary-container": "#d6a9ff",
        "tertiary-fixed-dim": "#7bd0ff",
        "on-background": "#d4e4fa",
        "on-secondary-fixed-variant": "#6900b3",
        "on-surface-variant": "#ccc3d8",
        "inverse-surface": "#d4e4fa",
        "tertiary-container": "#006e95",
        "inverse-on-surface": "#233143",
        "on-surface": "#d4e4fa",
        "surface-container-high": "#1c2b3c",
        "on-error": "#690005",
        "on-tertiary-container": "#caeaff",
        "surface-container-low": "#0d1c2d",
        "primary": "#d2bbff",
        "inverse-primary": "#732ee4",
        "background": "#051424",
        "secondary-fixed-dim": "#ddb7ff",
        "secondary-container": "#6f00be",
        "error-container": "#93000a",
        "surface-tint": "#d2bbff",
        "on-tertiary-fixed-variant": "#004c69",
        "surface-variant": "#273647",
        "primary-container": "#7c3aed",
        "surface-dim": "#051424",
        "on-primary-fixed-variant": "#5a00c6",
        "surface-bright": "#2c3a4c",
        "secondary": "#ddb7ff",
        "surface-container": "#122131",
        "on-tertiary": "#00354a",
        "outline": "#958da1",
        "on-tertiary-fixed": "#001e2c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "2rem",
        "stack-sm": "0.5rem",
        "gutter": "1.5rem",
        "stack-lg": "2rem",
        "margin-mobile": "1rem",
        "container-max": "1440px",
        "stack-md": "1rem",
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "display-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
